#应用的名称
spring:
  application:
    name: jaunty-micro-system
  profiles:
    active: dev #当前激活环境
#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.jaunty.domain.entity
