spring:
  application:
    name: jaunty-micro-eureka #应用的名称
  profiles:
    active: dev
server:
  port: 8001 #应用的端口
eureka:
  instance:
    hostname: localhost #设置主机名
  client:
    register-with-eureka: false #eureka自身不需要向自身注册，因此设置为false
    fetch-registry: false #是否检索服务，服务注册中心只需负责注册和发现服务，无需检索服务，因此设置为false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #注册地址：所有其他服务注册到这个地址

